replicaCount: 1

image:
  repository: vladimirkhil/sionline
  tag: 1.9.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: nginx
  pathType: Prefix
  hosts: []
  tls: []

resources: {}

config:
  serverDiscoveryUri: 'https://vladimirkhil.com/api/si/servers'
  apiUri: 'https://vladimirkhil.com/api/si'
  rootUri: '/'
  ads: '<b>Test ad</b>'
  onLoad: console.log('SIGame successfully loaded!');
  rewriteUrl: true
  forceHttps: true
  useMessagePackProtocol: false
  registerServiceWorker: false
  enableNoSleep: false
  askForConsent: false
