apiVersion: v1
entries:
  sionline:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-01-04T15:46:44.548225+03:00"
    description: SIGame client web application
    digest: 701a8df76f6898af21d63cd4910a5135282257de178f77b457cb612849fea840
    name: sionline
    type: application
    urls:
    - sionline-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2024-01-04T15:46:44.5472253+03:00"
    description: SIGame client web application
    digest: 216d55551f301e4ed03c9c6beab89c2a45184ea250c7a4b9c5b76b1b7c8a1bf6
    name: sionline
    type: application
    urls:
    - sionline-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2024-01-04T15:46:44.5462343+03:00"
    description: SIGame client web application
    digest: dc38ba71ce1a33da6d51ba726a657a50984903f44031ab63f1b0ecfbe17c6277
    name: sionline
    type: application
    urls:
    - sionline-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.2.2
    created: "2024-01-04T15:46:44.5457164+03:00"
    description: SIGame client web application
    digest: a5f7b00f61d3310ab33e6840a96d089246fe01f6aad7d158037448adf87d5195
    name: sionline
    type: application
    urls:
    - sionline-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2024-01-04T15:46:44.54465+03:00"
    description: SIGame client web application
    digest: fa7c585f7733dc1f91189b80ccaccb11ba2d529b524973b8868cff31ec607af3
    name: sionline
    type: application
    urls:
    - sionline-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2024-01-04T15:46:44.5441314+03:00"
    description: SIGame client web application
    digest: 446b5f93eea82e9f9b144f85c959878e5b137b385fd9c9fa0099c001977afd83
    name: sionline
    type: application
    urls:
    - sionline-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2024-01-04T15:46:44.5430906+03:00"
    description: SIGame client web application
    digest: 4323b8538663374819f0394b9db0c1b8f60b2dab86221bfc3d844240a04418e7
    name: sionline
    type: application
    urls:
    - sionline-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2024-01-04T15:46:44.5419525+03:00"
    description: SIGame client web application
    digest: 207bda237e4cb2c3712a67f1a4800c5779e5ef134ded1fb3c5b9dd54924a57cf
    name: sionline
    type: application
    urls:
    - sionline-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2024-01-04T15:46:44.5409153+03:00"
    description: SIGame client web application
    digest: c8bb7b0fa01c75c19bfa27d0d6c5857470d07412f22877864d144f67de7cd19f
    name: sionline
    type: application
    urls:
    - sionline-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-01-04T15:46:44.5403967+03:00"
    description: SIGame client web application
    digest: f2c06b7e890afb9ec401c37bff09b5efcfa23f206791c1975e761cda04cf246c
    name: sionline
    type: application
    urls:
    - sionline-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-01-04T15:46:44.5391231+03:00"
    description: SIGame client web application
    digest: 28537f2a0baf3b4db2918cab7a8e8c09eed0c7e5a83ae1fc729d11ff0d8f6485
    name: sionline
    type: application
    urls:
    - sionline-1.0.0.tgz
    version: 1.0.0
generated: "2024-01-04T15:46:44.5380818+03:00"
