{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sionline.fullname" . }}-ingress
  labels:
    {{- include "sionline.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts: {{ .Values.ingress.hosts }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ include "sionline.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}