apiVersion: v1
kind: Service
metadata:
  name: {{ include "sionline.fullname" . }}-nginx-metrics
  labels:
    {{- include "sionline.labels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.nginxPrometheusExporter.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "sionline.selectorLabels" . | nindent 4 }}
