name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install
      run: npm install
      
    - name: Test
      run: npm test
    
    - name: Build
      run: npm run build-prod
      
    - name: Set image tag
      run: echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.event.release.tag_name || github.ref }}"" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag $IMAGE_TAG
        docker push $IMAGE_TAG
